//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TestReflectionClassLibrary {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource1 {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource1() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TestReflectionClassLibrary.Resource1", typeof(Resource1).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Button_Cancel_EN {
            get {
                return ResourceManager.GetString("Button_Cancel_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Annulle.
        /// </summary>
        internal static string Button_Cancel_FR {
            get {
                return ResourceManager.GetString("Button_Cancel_FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Renunta.
        /// </summary>
        internal static string Button_Cancel_RO {
            get {
                return ResourceManager.GetString("Button_Cancel_RO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Button_Close_EN {
            get {
                return ResourceManager.GetString("Button_Close_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fermer.
        /// </summary>
        internal static string Button_Close_FR {
            get {
                return ResourceManager.GetString("Button_Close_FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inchide.
        /// </summary>
        internal static string Button_Close_RO {
            get {
                return ResourceManager.GetString("Button_Close_RO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string Button_OK_EN {
            get {
                return ResourceManager.GetString("Button_OK_EN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to D&apos;accord.
        /// </summary>
        internal static string Button_OK_FR {
            get {
                return ResourceManager.GetString("Button_OK_FR", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accepta.
        /// </summary>
        internal static string Button_OK_RO {
            get {
                return ResourceManager.GetString("Button_OK_RO", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap IMG1 {
            get {
                object obj = ResourceManager.GetObject("IMG1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
